In [14]:
import numpy as np
import pandas as pd
import os

In [15]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("abdullahcetin/mirichoi0218insurance")

print("Path to dataset files:", path)

df = pd.read_csv(path + "/" + os.listdir(path)[0])
df.head()

Path to dataset files: C:\Users\Welcome\.cache\kagglehub\datasets\abdullahcetin\mirichoi0218insurance\versions\1

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder,StandardScaler
from  sklearn.model_selection import train_test_split
from  sklearn.linear_model import SGDRegressor
from sklearn.pipeline import Pipeline

In [17]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns= ['charges']), df['charges'], test_size=0.2, random_state=42)

In [18]:
x_train.head()

      age     sex    bmi  children smoker     region
560    46  female  19.95         2     no  northwest
1285   47  female  24.32         0     no  northeast
1142   52  female  24.86         0     no  southeast
969    39  female  34.32         5     no  southeast
486    54  female  21.47         3     no  northwest

In [19]:
x_train.shape

(1070, 6)

In [20]:
tf1 = ColumnTransformer([
    ("sex_somker_region", OneHotEncoder(sparse_output= False, handle_unknown='ignore'),[1,4,5])
], remainder= 'passthrough')

In [21]:
pipe = Pipeline([
    ('tf',tf1),
    ('scale', StandardScaler()),
    ('model', SGDRegressor())

])

In [22]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('tf',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('sex_somker_region',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 4, 5])])),
                ('scale', StandardScaler()), ('model', SGDRegressor())])

In [23]:
import pickle
with open("model.pkl",'wb')as f:
    pickle.dump(pipe, f)